# Generated by Django 2.2.6 on 2020-01-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_article', models.TextField()),
                ('model_prediction', models.CharField(blank=True, max_length=5, null=True)),
                ('model_probability', models.FloatField(blank=True, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('article_valid', models.BooleanField(blank=True, null=True)),
                ('date_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.URLField(unique=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('url_valid', models.BooleanField(null=True)),
                ('date_checked', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(unique=True)),
                ('fakenews_num', models.IntegerField(default=0)),
                ('realnews_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsURLContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_content', models.TextField(blank=True, null=True)),
                ('model_prediction', models.CharField(blank=True, max_length=5, null=True)),
                ('model_probability', models.FloatField(blank=True, null=True)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fakecheck.NewsURL')),
            ],
        ),
        migrations.AddField(
            model_name='newsurl',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fakecheck.ThreatDomain'),
        ),
    ]
